### ISSUE TITLE
globals.context incorrect in event callbacks

### ISSUE THREAD

**Issue by ryanwe** [Sage/streamlinejs#279]
Hi @bjouhier!

I work at FiftyThree with @aseemk. We've been using `globals.context` in our express app to make it easier to track per-request, global state and it makes life a lot easier. However, I discovered that the global state can be incorrect when accessed from an event callback.

To repro, execute this code in parallel:
```
foo = i
globals.context['foo'] = i
i++

finish = ->
    # fails sporadically when executed in parallel. 
    # always succeeds when executed sequentially.
    assert.equal(globals.context['foo'], foo)

res.on 'finish', finish
```

I found a fix for this is to wrap `finish` with `globals.withContext`, passing in the current context.

Is this the recommended work-around or is there a better way of maintaining and resetting the global state?

I saw the trick for adding underscore to events but there is no mention of `globals` in events
https://github.com/Sage/streamlinejs/blob/master/FAQ.md#the-underscore-trick-is-designed-for-callbacks-but-not-events-how-do-i-deal-with-events which talks about 

Thanks!

**Comment by aseemk** [comment]
Thanks @ryanwe.

For reference, here is the code that (re)sets `globals.context` on every new Express request:

https://github.com/aseemk/express-streamline/blob/51e78a8f95abeb6770600e9575e5fe6a3dc41221/index.js#L148-L165

@bjouhier: Can you clarify maybe when `globals.context` is set/reset by Streamline vs. when it's not?

Thanks!

**Comment by aseemk** [comment]
Particularly when interfacing with native/non-Streamline code.

**Comment by bjouhier** [comment]
Hi Ryan and Aseem,

The global context is propagated across continuation callbacks (calls with `_`). It is also propagated to futures.

Unfortunately it is not propagated through event-oriented APIs, which is what express is using. This is not a problem if you have a processing pipeline with a series of non-streamline middlewares (which don't use the global context) followed by a request handler written with streamline. In this case you should allocate the new context just before dispatching to the streamline request handler. Don't allocate it at the beginning of the pipeline because it will be clobbered if some middleware code yields to the event loop.

You can allocate a new context with `globals.context = {}` but it is better to set it with `globals.withContext`. This function will restore the previous context before returning control to the event loop. This protects you against the risk of leaking the context to code which executes outside of any request (for example something that you scheduled with `setTimeout`).

In our application we have a little function that helps us detect context leaks. Here is the code:

```
if (config.system && config.system.verifyContextMillis) {
	(function() {
		var context = globals.context;
		setInterval(function() {
			if (globals.context !== context) {
				console.error("globals.context corrupted:\nEXPECTED: ", Object.keys(context), "\nGOT: ", Object.keys(globals.context));
				process.exit(1);
			}
		}, config.system.verifyContextMillis);
	})();
}
````

We enable this function in our dev/test deployments. Our app is multi-tenant and a context mixup would be catastrophic. So this function checks that a context which was created for request 1 will never be leaked and picked up by code originating from request 2.

`globals.withContext` is useful to propagate the context if you desynchronize code with `setTimeout` or `setImmediate`. See https://github.com/Sage/streamlinejs/blob/master/lib/compiler/flows._js#L302-307 for example.

**Comment by aseemk** [comment]
Sorry for the delay @bjouhier. That was a really helpful response, thanks!

I opened <https://github.com/aseemk/express-streamline/issues/25> to investigate this in express-streamline.

So can I summarize my understanding and you tell me if it's correct?

- Non-streamline (e.g. native) code calls a Streamline function: we should explicitly call `globals.withContext` before running our Streamline code. We would use a new empty object for the context if this is a new "thread" (e.g. request).

- Streamline code calls Streamline code (even if async'ly, i.e. getting back a future): nothing to do.

- Streamline code calls non-Streamline async code (e.g. `setTimeout`, or native `http.request`, etc.): wrap any callback in `globals.withContext`, using the current `globals.context` (like your trampoline example).

Is that all correct?

**Comment by bjouhier** [comment]
@aseemk Yes, you got it. 

Your third case (streamline -> non-streamline -> event loop -> event -> streamline) is typical of libraries that expose an evented API rather than a callback API. You often find two categories of events in these APIs:
* continuation events: typical case is a `connect` call which will trigger either a `connect` event or an `error` event. One of the two events is emitted and only once.
* _real_ events: typical case is the `request` event of an HTTP listener. The events are emitted many times and events can be completely uncorrelated.

I usually deal with continuation events by wrapping them with a regular callback API:
``` javascript
function connectWrapper(emitter, options, cb) {
  emitter.on('connect', function(connection) { cb && cb(null, connection); cb = null; }
  emitter.on('error', function(err) { cb && cb(err); cb = null; }
  emitter.connect(options);
}
```
Note: I'm a little paranoid about `cb` being called twice (never know what these libraries do exactly in case of errors) so I always test `cb` before firing and I reset it afterwards.

Then I don't need to worry about the context any more and I can just use streamline on my wrapper.

And the second case (_real_ events) is where I create a pseudo thread and allocate a new context or propagate an existing one.

**Comment by bjouhier** [comment]
Looks like this is solved. I'm closing for now. Don't hesitate to re-open.
