### ISSUE TITLE
Stale precompiled files under /home/<user>/.streamline?

### ISSUE THREAD

**Issue by yugangw-msft** [Sage/streamlinejs#290]
I am a contributor of [azure-cli](https://github.com/Azure/azure-xplat-cli), which has heavy usages of the streamline package. We had several issues logged that the product is broken due to weir errors, but after removed the .streamline folder, the problem went away.
My question here, is it a known issue? If we can't figure out, any recommended way to mitigate it? I have tried to add a npm post-install script to remove this folder, but that doesn't work well unless also use the flag of "--unsafe-perm" because npm invokes the script at a lower privilege by default. Or, any other options so to force the streamline to get refreshed? 
For reference, the following issue is the one just fired today. I can provide more if needed
https://github.com/Azure/azure-xplat-cli/issues/2196

**Comment by bjouhier** [comment]
This is strange and this is the first time I hear about the problem. 

Removing `.streamline` is a safe fix. It cannot hurt.

I would need more info to investigate. Renaming the corrupted dir instead of deleting it would help because then we can compare.

The `require` hooks are great during development but not really recommended for deployment. It would be better to precompile the `._js` files and distribute them as `.js`. This way the CLI will have a faster start and you won't take any risks with the cache. You can automate this with a `prepublish` hook in your `package.json`.

**Comment by yugangw-msft** [comment]
@bjouhier, for OSX and Windows, we pre-compile to .js files and package into the installer, and that work fine w/o streamline in the picture. Because our product is also a npm package, users can still install from npm directly, and they saw the random issue. 
Sure, I can back up the broken folder for you to investigate. At the same time, any way I can set flags to trigger streamline to recompile anything like reset all files' time stamp, or let streamline put files under the package folder, etc? I am trying to avoid deleting ".streamline" for the reason i mentioned earlier.  Thanks!

**Comment by bjouhier** [comment]
@yugangw-msft 
The `--force` option forces streamline to recompile, even if the cache is up-to-date. It should also fix the cache if it is corrupted. So maybe you can fix the problem by running a dummy action in `--force` mode in a post-install action.

But it would be better to publish precompiled files to NPM.

**Comment by yugangw-msft** [comment]
@bjouhier, thanks. I will just take your suggestion of not publish precompiled files to NPM.
So no further action needed, I am losing this issue.
