### ISSUE TITLE
`_coffee` no longer compiles non-Streamline CS files

### ISSUE THREAD

**Issue by gscottolson** [Sage/streamlinejs#315]
Hey Bruno. I am working through an upgrade from node 0.10.x → 4.2.x. After upgrading to `streamline@1.0.13`, I noticed that `_coffee` no longer compiles non-Streamline CS files.

```
> ls
test.coffee

> _coffee --compile test.coffee
> ls
test.coffee
               ^^^
               expected test.js
```

As expected, the CoffeeScript CLI works just fine.

```
> coffee --compile test.coffee
> ls
test.coffee    test.js
```

While this issue is minor and easy to fix, it caught me off guard. Any reason to not revert this behavior? If you leave it as-is, would you be willing to document this changes as part of the 1.x overhaul?

**Comment by aseemk** [comment]
+1: it'd be nice to have the old behavior back, but I can imagine it's not feasible since the whole pipeline changed (to Babel). =)

**Comment by bjouhier** [comment]
@aseemk @gscottolson This should be possible (and sorry for the regression). The compilation process is driven by streamline's CLI rather than by babel. So I should be able to fix it. 

Anyway, CoffeeScript is not handled as a babel plugin :disappointed: so streamline has to handle it in a special way.
