### ISSUE TITLE
Coffeescript default callback broken

### ISSUE THREAD

**Issue by shadinger** [Sage/streamlinejs#326]
Hey Bruno,

I'm using streamline + coffeescript in AWS Lambda. The following used to work with previous version of streamline but is now broken:

```
exports.handler = (event, context, _ = (e) -> throw e if e) ->
  context.succeed "Ok"
```

Error message:
```
/lib/node_modules/streamline/node_modules/babel-core/lib/transformation/file/index.js:585
      throw err;
      ^

SyntaxError: /home/ec2-user/Simple_Usage_Report/bug._coffee: unexpected _
  1 | (function() {
  2 |   exports.handler = function(event, context, _) {
> 3 |     if (_ == null) {
    |         ^
  4 |       _ = function(e) {
  5 |         if (e) {
  6 |           throw e;
    at File.buildCodeFrameError (/lib/node_modules/streamline/node_modules/babel-core/lib/transformation/file/index.js:436:15)
[...]
```

So for now I'm doing the following:

```
_handler = (event, context, _) ->
  context.succeed "Ok"

exports.handler = (event, context) ->
  cb = (e) -> throw e if e
  _handler(event, context, cb)
```

Is there a better way?
Thx

**Comment by bjouhier** [comment]
@shadinger This feature got lost in the big 1.0 rewrite. The problem is that it relies on a specific pattern generated by the CS compiler, and this pattern may change to take advantage of [ES6 default parameters](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters). So I would prefer to wait and re-implement this feature directly around ES6 default parameters (it does not yet work with ES6 either).

It is painful to have to write 2 functions for every handler. You can avoid this with a little helper function

```coffeescript
makeHandler = (fn) -> 
  (event, context) -> fn(event, context, (e) -> throw e if e)

exports.handler1 = makeHandler (event, context, _) ->
  context.succeed "Ok"

exports.handler2 = makeHandler (event, context, _) ->
  context.failed "ERR"
```

**Comment by shadinger** [comment]
Thanks Bruno,

I like it better that way. The default handler was not very readable for non coffee-script specialists.

Anyways, I struggled a little using streamline+coffeescript in AWS Lambda with the new version 1.0. Can I suggest that you add a section in the documentation about how to use streamline with AWS Lambda. Happy to help.
